-- MJM Picks — Grundschema (Modus A, vorbereitet für Modus B)
-- Angewendet am 28.08.2026 auf Projekt pmbubqfaiemixgimiiph (via MCP apply_migration "init_schema").
create extension if not exists pgcrypto;

create table public.admin_emails (
  email text primary key
);

create or replace function public.is_admin()
returns boolean
language sql stable security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.admin_emails
    where email = coalesce(auth.jwt() ->> 'email', '')
  );
$$;

create table public.categories (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  description text not null default '',
  hue text not null default 'violet',
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

create table public.products (
  id uuid primary key default gen_random_uuid(),
  pick_no int generated by default as identity unique,
  slug text not null unique,
  asin text check (asin is null or asin ~ '^[A-Z0-9]{10}$'),
  marketplace text not null default 'de',
  title text not null,
  brand text not null default '',
  status text not null default 'draft' check (status in ('draft','published','archived')),
  featured boolean not null default false,
  sort_order int not null default 0,
  source text not null default 'manual' check (source in ('manual','api')),
  image_url text,
  image_source text not null default 'none' check (image_source in ('press','own','none','api')),
  image_license text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.product_categories (
  product_id uuid not null references public.products(id) on delete cascade,
  category_id uuid not null references public.categories(id) on delete cascade,
  primary key (product_id, category_id)
);

create table public.product_editorial (
  product_id uuid primary key references public.products(id) on delete cascade,
  summary text not null default '',
  recommendation text not null default '',
  suited_for text not null default '',
  not_suited_for text not null default '',
  pros text[] not null default '{}',
  cons text[] not null default '{}',
  verdict text not null default '',
  alternative_product_id uuid references public.products(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table public.amazon_cache (
  asin text not null,
  marketplace text not null default 'de',
  payload jsonb not null default '{}'::jsonb,
  image_urls jsonb not null default '[]'::jsonb,
  features jsonb not null default '[]'::jsonb,
  offer jsonb,
  fetched_at timestamptz not null default now(),
  expires_at timestamptz not null default now() + interval '24 hours',
  offer_updated_at timestamptz,
  primary key (asin, marketplace)
);

create table public.site_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger trg_products_touch before update on public.products
  for each row execute function public.touch_updated_at();
create trigger trg_editorial_touch before update on public.product_editorial
  for each row execute function public.touch_updated_at();
create trigger trg_settings_touch before update on public.site_settings
  for each row execute function public.touch_updated_at();

alter table public.admin_emails enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_categories enable row level security;
alter table public.product_editorial enable row level security;
alter table public.amazon_cache enable row level security;
alter table public.site_settings enable row level security;

-- admin_emails: keine Policies = kein Zugriff (nur über is_admin/security definer)

create policy categories_read on public.categories for select using (true);
create policy categories_admin_all on public.categories for all
  using (public.is_admin()) with check (public.is_admin());

create policy products_read on public.products for select
  using (status = 'published' or public.is_admin());
create policy products_admin_ins on public.products for insert with check (public.is_admin());
create policy products_admin_upd on public.products for update
  using (public.is_admin()) with check (public.is_admin());
create policy products_admin_del on public.products for delete using (public.is_admin());

create policy pc_read on public.product_categories for select using (true);
create policy pc_admin_all on public.product_categories for all
  using (public.is_admin()) with check (public.is_admin());

create policy editorial_read on public.product_editorial for select
  using (exists (
    select 1 from public.products p
    where p.id = product_id and (p.status = 'published' or public.is_admin())
  ));
create policy editorial_admin_ins on public.product_editorial for insert with check (public.is_admin());
create policy editorial_admin_upd on public.product_editorial for update
  using (public.is_admin()) with check (public.is_admin());
create policy editorial_admin_del on public.product_editorial for delete using (public.is_admin());

create policy cache_read on public.amazon_cache for select using (true);
create policy cache_admin_all on public.amazon_cache for all
  using (public.is_admin()) with check (public.is_admin());

create policy settings_read on public.site_settings for select using (true);
create policy settings_admin_all on public.site_settings for all
  using (public.is_admin()) with check (public.is_admin());

-- Seeds
insert into public.admin_emails (email) values ('alex.mjm@proton.me');

insert into public.categories (slug, name, description, hue, sort_order) values
  ('gaming', 'Gaming', 'Peripherie und Ausrüstung, die sich im Alltag bewährt — nicht nur im Datenblatt.', 'violet', 1),
  ('pc-hardware', 'PC-Hardware', 'Komponenten und Zubehör für Rechner, die lange halten sollen.', 'cyan', 2),
  ('smart-home', 'Smart Home', 'Vernetzte Technik, die wirklich Alltag vereinfacht statt App-Frust zu erzeugen.', 'green', 3),
  ('technik', 'Technik', 'Gadgets und Alltagstechnik abseits der großen Kategorien.', 'amber', 4);

insert into public.site_settings (key, value) values
  ('partner_tag', '""'::jsonb),
  ('brand_name', '"MJM Picks"'::jsonb),
  ('site_url', '"https://www.mjm-picks.de"'::jsonb);
